spring.application.name=ServiceRegistery

#because it is running in by defualt 8761
server.port=8761


#server should not register itself
eureka.client.register-with-eureka=false

#server should not fetch registery
eureka.client.fetch-registry=false