spring.application.name=DoctorService

server.port=8082

# locate the address of the eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# enable circuit breaker for feign clients
spring.cloud.openfeign.circuitbreaker.enabled=true

# circuit breaker opens if 50% of calls fail
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50

# need at least 5 calls before circuit breaker starts checking failure rate
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5

# wait 10 seconds before trying again (open -> half_open)
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s

# allow 3 test calls in half_open state to check if service recovered
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3

#spring actuator - expose all endpoints to monitor circuit breaker
management.endpoints.web.exposure.include=*

#show circuit breaker health details
management.health.circuitbreakers.enabled=true